services:
- type: web
  name: fastapi-oauth
  env: python
  buildCommand: chmod +x build.sh && ./build.sh
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: fastapi-oauth-db
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: GOOGLE_REDIRECT_URI
    value: https://your-app-name.onrender.com/api/v1/auth/callback/google

databases:
- name: fastapi-oauth-db
  databaseName: fastapi_oauth
  user: fastapi_oauth_user
